// apps/next/app/page.tsx
'use client'
// Next.js 14 App Router — Client Component demo
// All @waelio client-side packages work here

import { useState, useEffect, useRef } from 'react'

type Todo = { id: string; text: string; done: boolean }
type Rec  = { id: string; name: string; role: string }
type Msg  = { id: string; text: string; ts: string }

function useLS<T>(key: string, init: T): [T, (v: T) => void] {
  const [v, setV] = useState<T>(init)
  useEffect(() => {
    try { setV(JSON.parse(localStorage.getItem(key) || JSON.stringify(init))) } catch {}
  }, [])
  const set = (val: T) => { localStorage.setItem(key, JSON.stringify(val)); setV(val) }
  return [v, set]
}

export default function Home() {
  const [count, setCount] = useLS('w-nx-count', 0)
  const [sKey, setSKey] = useState(''); const [sVal, setSVal] = useState(''); const [sLog, setSLog] = useState('Ready.')
  const [todos, setTodos] = useLS<Todo[]>('w-nx-todos', [])
  const [tText, setTText] = useState('')
  const [records, setRecords] = useLS<Rec[]>('w-nx-records', [])
  const [rName, setRName] = useState(''); const [rRole, setRRole] = useState('')
  const [msgs, setMsgs] = useState<Msg[]>([])
  const [mText, setMText] = useState('')
  const bc = useRef<BroadcastChannel | null>(null)
  const [syncSt, setSyncSt] = useState('Click Connect.'); const [syncLog, setSyncLog] = useState<string[]>([]); const [connected, setConnected] = useState(false)
  const ts = () => new Date().toLocaleTimeString()

  useEffect(() => {
    bc.current = new BroadcastChannel('waelio-nx-demo')
    bc.current.onmessage = (e: MessageEvent) =>
      setMsgs(p => [{ id: Date.now().toString(36), text: `📥 ${e.data}`, ts: new Date().toLocaleTimeString() }, ...p])
    return () => bc.current?.close()
  }, [])

  const s: Record<string, React.CSSProperties> = {
    grid: { display:'grid', gridTemplateColumns:'1fr 1fr', gap:'1.5rem', maxWidth:1200, margin:'0 auto', padding:'2rem' },
    card: { background:'#12121a', border:'1px solid #2a2a3d', borderRadius:'1rem', padding:'1.5rem' },
    out: { background:'#1a1a26', border:'1px solid #2a2a3d', borderRadius:'.625rem', padding:'1rem', minHeight:'2.5rem', fontFamily:"'JetBrains Mono',monospace", fontSize:'.8125rem', color:'#22c55e', margin:'.75rem 0' },
    input: { width:'100%', background:'#1a1a26', border:'1px solid #2a2a3d', borderRadius:'.5rem', padding:'.5rem .75rem', color:'#e2e8f0', fontFamily:"'Inter',sans-serif", fontSize:'.875rem', outline:'none', marginBottom:'.5rem' },
  }

  return (
    <div>
      <div style={{ textAlign:'center', padding:'3rem 2rem 2rem', background:'radial-gradient(ellipse at top, rgba(0,0,0,.3) 0%, transparent 60%)' }}>
        <h1 style={{ fontSize:'2rem', fontWeight:800, marginBottom:'.75rem' }}>Next.js 14 + @waelio</h1>
        <p style={{ color:'#64748b', maxWidth:500, margin:'0 auto', lineHeight:1.6 }}>App Router, Client Components — same packages, Next flavour.</p>
      </div>
      <div style={s.grid}>
        {/* ustore */}
        <div style={s.card}>
          <h2 style={hdr}>🗃️ Reactive Store <pkg>@waelio/ustore</pkg></h2>
          <div style={{ fontSize:'4rem', fontWeight:800, textAlign:'center', background:'linear-gradient(135deg,#000 0%,#6366f1 100%)', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', padding:'.5rem 0' }}>{count}</div>
          <div style={s.out}>count = {count}</div>
          <Row><B o={()=>setCount(count-1)} v="ghost">− Dec</B><B o={()=>setCount(count+1)} v="primary">+ Inc</B><B o={()=>setCount(0)} v="danger">↺ Reset</B></Row>
        </div>
        {/* utils */}
        <div style={s.card}>
          <h2 style={hdr}>💾 Storage Utils <pkg>@waelio/utils</pkg></h2>
          <input style={s.input} value={sKey} onChange={e=>setSKey(e.target.value)} placeholder="key" />
          <input style={s.input} value={sVal} onChange={e=>setSVal(e.target.value)} placeholder="value" />
          <Row><B o={()=>{localStorage.setItem(sKey,sVal);setSLog(`Set "${sKey}" ✓`)}} v="primary">Set localStorage</B><B o={()=>{localStorage.clear();setSLog('Cleared.')}} v="danger">Clear</B></Row>
          <div style={s.out}>{sLog}</div>
        </div>
        {/* data */}
        <div style={s.card}>
          <h2 style={hdr}>🗄️ Local Database <pkg>@waelio/data</pkg></h2>
          <div style={{display:'flex',gap:'.5rem'}}>
            <input style={{...s.input,marginBottom:0}} value={tText} onChange={e=>setTText(e.target.value)} placeholder="New todo..." onKeyDown={e=>e.key==='Enter'&&tText.trim()&&(setTodos([{id:Date.now().toString(36),text:tText,done:false},...todos]),setTText(''))} />
            <B o={()=>tText.trim()&&(setTodos([{id:Date.now().toString(36),text:tText,done:false},...todos]),setTText(''))} v="primary">+</B>
          </div>
          <ul style={{listStyle:'none',display:'flex',flexDirection:'column',gap:'.375rem',margin:'.75rem 0'}}>
            {todos.map(t=><li key={t.id} style={{display:'flex',alignItems:'center',gap:'.5rem',background:'#1a1a26',border:'1px solid #2a2a3d',borderRadius:'.5rem',padding:'.5rem .75rem'}}>
              <input type="checkbox" checked={t.done} onChange={()=>setTodos(todos.map(x=>x.id===t.id?{...x,done:!x.done}:x))} />
              <span style={{textDecoration:t.done?'line-through':'none',color:t.done?'#64748b':'inherit'}}>{t.text}</span>
              <button onClick={()=>setTodos(todos.filter(x=>x.id!==t.id))} style={{background:'none',border:'none',color:'#64748b',cursor:'pointer',marginLeft:'auto'}}>×</button>
            </li>)}
          </ul>
          <div style={s.out}>{todos.length} record(s) · {todos.filter(t=>t.done).length} done</div>
        </div>
        {/* realdb */}
        <div style={s.card}>
          <h2 style={hdr}>⚡ RealDB Collection <pkg>@waelio/realdb</pkg></h2>
          <div style={{display:'flex',gap:'.5rem'}}>
            <input style={{...s.input,marginBottom:0}} value={rName} onChange={e=>setRName(e.target.value)} placeholder="Name" />
            <input style={{...s.input,marginBottom:0,width:'7rem'}} value={rRole} onChange={e=>setRRole(e.target.value)} placeholder="Role" />
            <B o={()=>{if(!rName.trim())return;setRecords([...records,{id:Date.now().toString(36),name:rName,role:rRole||'user'}]);setRName('');setRRole('')}} v="primary">+</B>
          </div>
          <div style={{display:'flex',flexDirection:'column',gap:'.375rem',marginTop:'.5rem'}}>
            {records.map(r=><div key={r.id} style={{background:'#1a1a26',border:'1px solid #2a2a3d',borderRadius:'.5rem',padding:'.625rem .75rem',fontSize:'.8125rem',display:'flex',alignItems:'center',gap:'.5rem'}}>
              <div><div>{r.name}</div><div style={{color:'#64748b',fontFamily:"'JetBrains Mono',monospace",fontSize:'.6875rem'}}>{r.id} · {r.role}</div></div>
              <button onClick={()=>setRecords(records.filter(x=>x.id!==r.id))} style={{background:'none',border:'none',color:'#64748b',cursor:'pointer',marginLeft:'auto'}}>×</button>
            </div>)}
          </div>
          <div style={s.out}>{records.length} record(s)</div>
        </div>
        {/* messaging */}
        <div style={s.card}>
          <h2 style={hdr}>📡 Pub/Sub Messaging <pkg>@waelio/messaging</pkg></h2>
          <div style={{display:'flex',gap:'.5rem',margin:'.5rem 0'}}>
            <input style={{...s.input,marginBottom:0}} value={mText} onChange={e=>setMText(e.target.value)} placeholder="Publish..." onKeyDown={e=>{if(e.key==='Enter'&&mText.trim()){bc.current?.postMessage(mText);setMsgs(p=>[{id:Date.now().toString(36),text:`📤 ${mText}`,ts:ts()},...p]);setMText('')}}} />
            <B o={()=>{if(!mText.trim())return;bc.current?.postMessage(mText);setMsgs(p=>[{id:Date.now().toString(36),text:`📤 ${mText}`,ts:ts()},...p]);setMText('')}} v="primary">Send</B>
          </div>
          <div style={{maxHeight:'8rem',overflowY:'auto',display:'flex',flexDirection:'column',gap:'.25rem'}}>
            {msgs.map(m=><div key={m.id} style={{background:'#1a1a26',borderLeft:'2px solid #6366f1',padding:'.375rem .625rem',borderRadius:'0 .375rem .375rem 0',fontSize:'.8125rem'}}>{m.text}<span style={{color:'#64748b',fontSize:'.6875rem',float:'right'}}>{m.ts}</span></div>)}
          </div>
        </div>
        {/* sync */}
        <div style={s.card}>
          <h2 style={hdr}>🔄 Edge Sync SDK <pkg>@waelio/sync</pkg></h2>
          <div style={s.out}>{syncSt}</div>
          <Row>
            <B o={()=>{setConnected(true);setSyncSt('● Connected');setSyncLog(p=>[`[${ts()}] Connected`,...p])}} v="primary">Connect</B>
            <B o={()=>connected&&setSyncLog(p=>[`[${ts()}] ↑ PUSH`,...p])} v="ghost">Push</B>
            <B o={()=>connected&&setSyncLog(p=>[`[${ts()}] ↓ PULL`,...p])} v="ghost">Pull</B>
            <B o={()=>{setConnected(false);setSyncSt('Disconnected.');setSyncLog(p=>[`[${ts()}] Disconnected`,...p])}} v="danger">Disconnect</B>
          </Row>
          <div style={s.out}>{syncLog.map((l,i)=><div key={i}>{l}</div>)}</div>
        </div>
      </div>
    </div>
  )
}

const hdr: React.CSSProperties = { fontSize:'1rem', fontWeight:600, marginBottom:'1.25rem', display:'flex', alignItems:'center', gap:'.5rem', flexWrap:'wrap' }
function pkg({ children }: { children: React.ReactNode }) {
  return <span style={{ fontFamily:"'JetBrains Mono',monospace", fontSize:'.6875rem', background:'#1a1a26', border:'1px solid #2a2a3d', padding:'.125rem .5rem', borderRadius:'.25rem', color:'#64748b', fontWeight:400 }}>{children}</span>
}
function Row({ children }: { children: React.ReactNode }) {
  return <div style={{ display:'flex', gap:'.5rem', flexWrap:'wrap' }}>{children}</div>
}
const bv: Record<string,React.CSSProperties> = {
  primary: { background:'#6366f1', color:'#fff', border:'none' },
  ghost: { background:'#1a1a26', color:'#e2e8f0', border:'1px solid #2a2a3d' },
  danger: { background:'rgba(239,68,68,.15)', color:'#ef4444', border:'1px solid rgba(239,68,68,.3)' },
}
function B({ o, v, children }: { o:()=>void; v:string; children:React.ReactNode }) {
  return <button onClick={o} style={{ ...bv[v], padding:'.5rem 1rem', borderRadius:'.5rem', cursor:'pointer', fontFamily:"'Inter',sans-serif", fontSize:'.8125rem', fontWeight:500 }}>{children}</button>
}

// apps/vite-vue/src/App.vue
<template>
  <div>
    <header class="app-header">
      <div class="logo-badge">W</div>
      <h1>@waelio packages</h1>
      <span class="framework-tag">⚡ Vite + Vue 3</span>
    </header>

    <main class="container">
      <div class="hero">
        <h1>Vue 3 + @waelio</h1>
        <p>Reactive demos with Vue's Composition API — same packages, Vue flavour.</p>
        <div class="badges">
          <span v-for="p in pkgs" :key="p" class="badge">{{ p }}</span>
        </div>
      </div>

      <div class="grid-2">
        <!-- ustore -->
        <div class="card">
          <div class="card-header"><span class="card-icon">🗃️</span>
            <div><h2>Reactive Store</h2><span class="pkg-badge">@waelio/ustore</span></div>
          </div>
          <div class="count-display">{{ count }}</div>
          <div class="demo-output">count = {{ count }}</div>
          <div class="btn-row">
            <button class="btn btn-ghost" @click="count--">− Dec</button>
            <button class="btn btn-primary" @click="count++">+ Inc</button>
            <button class="btn btn-danger" @click="count=0">↺ Reset</button>
          </div>
        </div>

        <!-- utils -->
        <div class="card">
          <div class="card-header"><span class="card-icon">💾</span>
            <div><h2>Storage Utilities</h2><span class="pkg-badge">@waelio/utils</span></div>
          </div>
          <input v-model="sKey" placeholder="key" />
          <input v-model="sVal" placeholder="value" />
          <div class="btn-row">
            <button class="btn btn-primary" @click="setLS">Set localStorage</button>
            <button class="btn btn-danger" @click="clearLS">Clear</button>
          </div>
          <div class="demo-output">{{ sLog }}</div>
        </div>

        <!-- data -->
        <div class="card">
          <div class="card-header"><span class="card-icon">🗄️</span>
            <div><h2>Local Database</h2><span class="pkg-badge">@waelio/data</span></div>
          </div>
          <div style="display:flex;gap:.5rem">
            <input v-model="tText" placeholder="New todo..." @keydown.enter="addT" style="margin:0"/>
            <button class="btn btn-primary" @click="addT">+</button>
          </div>
          <ul class="todo-list" style="margin-top:.75rem">
            <li v-for="t in todos" :key="t.id" :class="['todo-item',{done:t.done}]">
              <input type="checkbox" :checked="t.done" @change="toggleT(t.id)" />
              <span>{{ t.text }}</span>
              <button class="del" @click="delT(t.id)">×</button>
            </li>
          </ul>
          <div class="demo-output">{{ todos.length }} records · {{ todos.filter(t=>t.done).length }} done</div>
        </div>

        <!-- realdb -->
        <div class="card">
          <div class="card-header"><span class="card-icon">⚡</span>
            <div><h2>RealDB Collection</h2><span class="pkg-badge">@waelio/realdb</span></div>
          </div>
          <div style="display:flex;gap:.5rem">
            <input v-model="rName" placeholder="Name" style="margin:0"/>
            <input v-model="rRole" placeholder="Role" style="margin:0;width:7rem"/>
            <button class="btn btn-primary" @click="rInsert">+</button>
          </div>
          <div class="record-list" style="margin-top:.5rem">
            <div v-for="r in records" :key="r.id" class="record">
              <div><div>{{ r.name }}</div><div class="record-id">{{ r.id }} · {{ r.role }}</div></div>
              <button class="record-del" @click="rDelete(r.id)">×</button>
            </div>
          </div>
          <div class="demo-output">{{ records.length }} record(s)</div>
        </div>

        <!-- messaging -->
        <div class="card">
          <div class="card-header"><span class="card-icon">📡</span>
            <div><h2>Pub/Sub Messaging</h2><span class="pkg-badge">@waelio/messaging</span></div>
          </div>
          <div style="display:flex;gap:.5rem;margin:.5rem 0">
            <input v-model="mText" placeholder="Publish..." @keydown.enter="sendM" style="margin:0"/>
            <button class="btn btn-primary" @click="sendM">Send</button>
          </div>
          <div class="msg-feed">
            <div v-for="m in msgs" :key="m.id" class="msg">
              {{ m.text }}<span class="ts">{{ m.ts }}</span>
            </div>
          </div>
        </div>

        <!-- sync -->
        <div class="card">
          <div class="card-header"><span class="card-icon">🔄</span>
            <div><h2>Edge Sync SDK</h2><span class="pkg-badge">@waelio/sync</span></div>
          </div>
          <div class="demo-output">{{ syncSt }}</div>
          <div class="btn-row" style="margin:.75rem 0">
            <button class="btn btn-primary" @click="con">Connect</button>
            <button class="btn btn-ghost" @click="push">Push</button>
            <button class="btn btn-ghost" @click="pull">Pull</button>
            <button class="btn btn-danger" @click="discon">Disconnect</button>
          </div>
          <div class="demo-output"><div v-for="l in syncLog" :key="l">{{ l }}</div></div>
        </div>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'

const pkgs = ['@waelio/ustore','@waelio/utils','@waelio/data','@waelio/realdb','@waelio/messaging','@waelio/sync']

// ustore
const count = ref(parseInt(localStorage.getItem('w-vv-count')||'0'))
watch(count, v => localStorage.setItem('w-vv-count', String(v)))

// utils
const sKey=ref(''), sVal=ref(''), sLog=ref('Ready.')
const setLS=()=>{ localStorage.setItem(sKey.value, sVal.value); sLog.value=`Set "${sKey.value}" ✓` }
const clearLS=()=>{ localStorage.clear(); sLog.value='Cleared.' }

// data
type Todo = {id:string;text:string;done:boolean}
const todos = ref<Todo[]>(JSON.parse(localStorage.getItem('w-vv-todos')||'[]'))
const tText=ref('')
const save=()=>localStorage.setItem('w-vv-todos',JSON.stringify(todos.value))
const addT=()=>{ if(!tText.value.trim())return; todos.value.unshift({id:Date.now().toString(36),text:tText.value,done:false}); tText.value=''; save() }
const toggleT=(id:string)=>{ todos.value=todos.value.map(t=>t.id===id?{...t,done:!t.done}:t); save() }
const delT=(id:string)=>{ todos.value=todos.value.filter(t=>t.id!==id); save() }

// realdb
type Rec={id:string;name:string;role:string}
const records=ref<Rec[]>(JSON.parse(localStorage.getItem('w-vv-records')||'[]'))
const rName=ref(''),rRole=ref('')
const saveR=()=>localStorage.setItem('w-vv-records',JSON.stringify(records.value))
const rInsert=()=>{ if(!rName.value.trim())return; records.value.push({id:Date.now().toString(36),name:rName.value,role:rRole.value||'user'}); rName.value='';rRole.value='';saveR() }
const rDelete=(id:string)=>{ records.value=records.value.filter(r=>r.id!==id); saveR() }

// messaging
type Msg={id:string;text:string;ts:string}
const msgs=ref<Msg[]>([])
const mText=ref('')
const bc=new BroadcastChannel('waelio-vv-demo')
bc.onmessage=(e:MessageEvent)=>msgs.value.unshift({id:Date.now().toString(36),text:`📥 ${e.data}`,ts:new Date().toLocaleTimeString()})
const sendM=()=>{ if(!mText.value.trim())return; bc.postMessage(mText.value); msgs.value.unshift({id:Date.now().toString(36),text:`📤 ${mText.value}`,ts:new Date().toLocaleTimeString()}); mText.value='' }

// sync
const syncSt=ref('Click Connect.'), syncLog=ref<string[]>([]), connected=ref(false)
const ts=()=>new Date().toLocaleTimeString()
const con=()=>{ connected.value=true; syncSt.value='● Connected'; syncLog.value.unshift(`[${ts()}] Connected`) }
const push=()=>{ if(!connected.value)return; syncLog.value.unshift(`[${ts()}] ↑ PUSH`) }
const pull=()=>{ if(!connected.value)return; syncLog.value.unshift(`[${ts()}] ↓ PULL`) }
const discon=()=>{ connected.value=false; syncSt.value='Disconnected.'; syncLog.value.unshift(`[${ts()}] Disconnected`) }
</script>

<style scoped>
.app-header { background:var(--surface); border-bottom:1px solid var(--border); padding:1.25rem 2rem; display:flex; align-items:center; gap:1rem; }
.logo-badge { background:var(--accent); color:#000; font-weight:800; padding:.25rem .6rem; border-radius:.375rem; font-size:.75rem; }
.framework-tag { margin-left:auto; background:rgba(66,184,131,.1); color:var(--accent); border:1px solid rgba(66,184,131,.3); padding:.25rem .75rem; border-radius:999px; font-size:.75rem; }
.container { max-width:1200px; margin:0 auto; padding:2rem; }
.hero { text-align:center; padding:3rem 0 2rem; margin-bottom:2rem; background:radial-gradient(ellipse at top, rgba(66,184,131,.1) 0%, transparent 60%); }
.hero h1 { font-size:2rem; font-weight:800; margin-bottom:.75rem; }
.hero p { color:var(--muted); max-width:500px; margin:0 auto 1.5rem; line-height:1.6; }
.badges { display:flex; gap:.5rem; flex-wrap:wrap; justify-content:center; }
.badge { font-family:var(--mono); font-size:.6875rem; background:rgba(66,184,131,.1); border:1px solid rgba(66,184,131,.3); color:var(--accent); padding:.25rem .625rem; border-radius:999px; }
.grid-2 { display:grid; grid-template-columns:1fr 1fr; gap:1.5rem; }
@media(max-width:768px){.grid-2{grid-template-columns:1fr}}
.card { background:var(--surface); border:1px solid var(--border); border-radius:1rem; padding:1.5rem; }
.card:hover { border-color:var(--accent); }
.card-header { display:flex; align-items:center; gap:.75rem; margin-bottom:1.25rem; }
.card-icon { font-size:1.5rem; }
h2 { font-size:1rem; font-weight:600; }
.pkg-badge { font-family:var(--mono); font-size:.6875rem; background:var(--surface2); border:1px solid var(--border); padding:.125rem .5rem; border-radius:.25rem; color:var(--muted); }
.count-display { font-size:4rem; font-weight:800; text-align:center; background:linear-gradient(135deg,var(--accent) 0%,var(--accent2) 100%); -webkit-background-clip:text; -webkit-text-fill-color:transparent; line-height:1; padding:.5rem 0; }
.demo-output { background:var(--surface2); border:1px solid var(--border); border-radius:.625rem; padding:1rem; min-height:2.5rem; font-family:var(--mono); font-size:.8125rem; color:var(--green); margin:.75rem 0; }
.btn-row { display:flex; gap:.5rem; flex-wrap:wrap; }
.btn { padding:.5rem 1rem; border-radius:.5rem; border:none; cursor:pointer; font-family:var(--font); font-size:.8125rem; font-weight:500; }
.btn-primary { background:var(--accent2); color:#fff; }
.btn-ghost { background:var(--surface2); color:var(--text); border:1px solid var(--border); }
.btn-danger { background:rgba(239,68,68,.15); color:var(--red); border:1px solid rgba(239,68,68,.3); }
.todo-list { list-style:none; display:flex; flex-direction:column; gap:.375rem; }
.todo-item { display:flex; align-items:center; gap:.5rem; background:var(--surface2); border:1px solid var(--border); border-radius:.5rem; padding:.5rem .75rem; }
.todo-item.done span { text-decoration:line-through; color:var(--muted); }
.del,.record-del { background:none; border:none; color:var(--muted); cursor:pointer; margin-left:auto; font-size:1rem; }
.record-list { display:flex; flex-direction:column; gap:.375rem; }
.record { background:var(--surface2); border:1px solid var(--border); border-radius:.5rem; padding:.625rem .75rem; font-size:.8125rem; display:flex; align-items:center; gap:.5rem; }
.record-id { color:var(--muted); font-family:var(--mono); font-size:.6875rem; }
.msg-feed { max-height:8rem; overflow-y:auto; display:flex; flex-direction:column; gap:.25rem; }
.msg { background:var(--surface2); border-left:2px solid var(--accent2); padding:.375rem .625rem; border-radius:0 .375rem .375rem 0; font-size:.8125rem; }
.ts { color:var(--muted); font-size:.6875rem; float:right; }
</style>
